# 데이터 가공

## 패키지 임포트

In [2]:
# 넘파이와 판다스 라이브러리 가져오기
import numpy as np
import pandas as pd

In [3]:
# 데이터셋 불러오기
meteor_showers = pd.read_csv('data/meteorshowers.csv')
constellations = pd.read_csv('data/constellations.csv')
moon_phases = pd.read_csv('data/moonphases.csv')
cities = pd.read_csv('data/cities.csv')

In [10]:
# 유성우 데이터 확인하기
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [11]:
# 달의 위상 데이터 확인하기
moon_phases

        month  day      moonphase specialevent
0     january    1            NaN          NaN
1     january    2  first quarter          NaN
2     january    3            NaN          NaN
3     january    4            NaN          NaN
4     january    5            NaN          NaN
..        ...  ...            ...          ...
361  december   27            NaN          NaN
362  december   28            NaN          NaN
363  december   29      full moon          NaN
364  december   30            NaN          NaN
365  december   31            NaN          NaN

[366 rows x 4 columns]

In [14]:
moon_phases.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month         366 non-null    str
 1   day           366 non-null    int64
 2   moonphase     50 non-null     str
 3   specialevent  10 non-null     str
dtypes: int64(1), str(3)
memory usage: 11.6 KB

In [12]:
# 별자리 데이터 확인하기
constellations

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

In [13]:
# 도시 데이터 확인하기기
cities

                        city  latitude               country
0                  Abu Dhabi     24.47  United Arab Emirates
1                      Abuja      9.07               Nigeria
2                      Accra      5.55                 Ghana
3                  Adamstown    -25.07      Pitcairn Islands
4                Addis Ababa      9.02              Ethiopia
..                       ...       ...                   ...
251  Abidjan(former capital)      6.82           Ivory Coast
252                  Yaounde      3.87              Cameroon
253          Yaren(de facto)     -0.53                 Nauru
254                  Yerevan     40.18               Armenia
255                   Zagreb     45.82               Croatia

[256 rows x 3 columns]

In [6]:
# meteor_showers 유성우 정보 조회
meteor_showers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5 non-null      str
 1   radiant              5 non-null      str
 2   bestmonth            5 non-null      str
 3   startmonth           5 non-null      str
 4   startday             5 non-null      int64
 5   endmonth             5 non-null      str
 6   endday               5 non-null      int64
 7   hemisphere           5 non-null      str
 8   preferredhemisphere  5 non-null      str
dtypes: int64(2), str(7)
memory usage: 492.0 bytes

## 컬럼 dtype 변경(월 이름)

In [5]:
# 유성우 월 이름 변경
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [3]:
moon_phases

        month  day      moonphase specialevent
0     january    1            NaN          NaN
1     january    2  first quarter          NaN
2     january    3            NaN          NaN
3     january    4            NaN          NaN
4     january    5            NaN          NaN
..        ...  ...            ...          ...
361  december   27            NaN          NaN
362  december   28            NaN          NaN
363  december   29      full moon          NaN
364  december   30            NaN          NaN
365  december   31            NaN          NaN

[366 rows x 4 columns]

In [3]:
moon_phases['month'].unique()

<StringArray>
[  'january',  'february',     'march',     'april',       'may',      'june',
      'july',    'august', 'september',   'october',  'november',  'december']
Length: 12, dtype: str

In [6]:
# 월명을 숫자로 변환하기 위한 딕셔너리 생성 months
months = {'january': 1, 
          'february': 2, 
          'march': 3, 
          'april': 4, 
          'may': 5, 
          'june': 6, 
          'july': 7, 
          'august': 8, 
          'september': 9, 
          'october': 10, 
          'november': 11, 
          'december': 12}

In [19]:
# 유성우데이터프레임의 월명을 숫자로 변환 map 메소드 사용
meteor_showers['bestmonth'].map(months)
# meteor_showers['startmonth'].apply(lambda x: months[x] )
# meteor_showers['endmonth'].replace(months)

0     4
1     5
2    10
3     8
4    11
Name: bestmonth, dtype: int64

In [20]:
meteor_showers['bestmonth'] = meteor_showers['bestmonth'].map(months)

In [22]:
meteor_showers['startmonth'] = meteor_showers['startmonth'].map(months)
meteor_showers['endmonth'] = meteor_showers['endmonth'].map(months)

In [23]:
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,8,24,northern,northern
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern"

In [24]:
# 유성우 월명이 숫자로 변경되었는지 정보 확인
meteor_showers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5 non-null      str
 1   radiant              5 non-null      str
 2   bestmonth            5 non-null      int64
 3   startmonth           5 non-null      int64
 4   startday             5 non-null      int64
 5   endmonth             5 non-null      int64
 6   endday               5 non-null      int64
 7   hemisphere           5 non-null      str
 8   preferredhemisphere  5 non-null      str
dtypes: int64(5), str(4)
memory usage: 492.0 bytes

In [29]:
# 다른 데이터프레임(달의위상, 별자리)도 월명을 숫자로 변환
moon_phases['month'] =moon_phases['month'].map(months)
moon_phases

     month  day      moonphase specialevent
0        1    1            NaN          NaN
1        1    2  first quarter          NaN
2        1    3            NaN          NaN
3        1    4            NaN          NaN
4        1    5            NaN          NaN
..     ...  ...            ...          ...
361     12   27            NaN          NaN
362     12   28            NaN          NaN
363     12   29      full moon          NaN
364     12   30            NaN          NaN
365     12   31            NaN          NaN

[366 rows x 4 columns]

In [33]:
moon_phases.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month         366 non-null    int64
 1   day           366 non-null    int64
 2   moonphase     50 non-null     str
 3   specialevent  10 non-null     str
dtypes: int64(2), str(2)
memory usage: 11.6 KB

In [32]:
constellations['bestmonth'] = constellations['bestmonth'].map(months)
constellations

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern
3       Perseus         12             90          -35    21:00   northern
4           Leo          4             90           65    21:00   northern

In [225]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [33]:
# 달의위상
moon_phases

     month  day      moonphase specialevent
0        1    1            NaN          NaN
1        1    2  first quarter          NaN
2        1    3            NaN          NaN
3        1    4            NaN          NaN
4        1    5            NaN          NaN
..     ...  ...            ...          ...
361     12   27            NaN          NaN
362     12   28            NaN          NaN
363     12   29      full moon          NaN
364     12   30            NaN          NaN
365     12   31            NaN          NaN

[366 rows x 4 columns]

In [16]:
moon_phases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month         366 non-null    int64
 1   day           366 non-null    int64
 2   moonphase     50 non-null     object
 3   specialevent  10 non-null     object
dtypes: int64(2), object(2)
memory usage: 11.6+ KB

In [183]:
# 별자리
constellations

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern
3       Perseus         12             90          -35    21:00   northern
4           Leo          4             90           65    21:00   northern

In [36]:
constellations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   constellation  5 non-null      object
 1   bestmonth      5 non-null      int64
 2   latitudestart  5 non-null      int64
 3   latitudeend    5 non-null      int64
 4   besttime       5 non-null      object
 5   hemisphere     5 non-null      object
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

## 일자 정보 Datetime으로 변환(startdate 컬럼 생성)

In [34]:
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,8,24,northern,northern
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern"

In [42]:
# 유성우 데이터프레임의 새로운 컬럼에 일자 정보를 datatime(20240428)으로 변환하여 저장, startdate, enddate
# startdate 컬럼 추가 20200428
# 2020, 4, 21 -> 20200421 -> 2020-04-28
# 2020 * 10000 +meteor_showers['startmonth'] * 100 + meteor_showers['startday']
pd.to_datetime(2020 * 10000 +meteor_showers['startmonth'] * 100 + meteor_showers['startday'], format='%Y%m%d')

0   2020-04-21
1   2020-04-19
2   2020-10-02
3   2020-07-14
4   2020-11-06
dtype: datetime64[us]

In [45]:
meteor_showers['startdate'] = pd.to_datetime(2020 * 10000 +meteor_showers['startmonth'] * 100 + meteor_showers['startday'], format='%Y%m%d')
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06

In [46]:
meteor_showers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5 non-null      str
 1   radiant              5 non-null      str
 2   bestmonth            5 non-null      int64
 3   startmonth           5 non-null      int64
 4   startday             5 non-null      int64
 5   endmonth             5 non-null      int64
 6   endday               5 non-null      int64
 7   hemisphere           5 non-null      str
 8   preferredhemisphere  5 non-null      str
 9   startdate            5 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(5), str(4)
memory usage: 532.0 bytes

In [47]:
# 유성우 데이터프레임의 새로운 컬럼에 일자 정보를 datatime(20240428)으로 변환하여 저장, startdate, enddate
# enddate 컬럼 추가
meteor_showers['enddate'] = pd.to_datetime(2020 * 10000 +meteor_showers['endmonth'] * 100 + meteor_showers['endday'], format='%Y%m%d')
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14,2020-08-24
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06,2020-11-30

In [48]:
moon_phases

     month  day      moonphase specialevent
0        1    1            NaN          NaN
1        1    2  first quarter          NaN
2        1    3            NaN          NaN
3        1    4            NaN          NaN
4        1    5            NaN          NaN
..     ...  ...            ...          ...
361     12   27            NaN          NaN
362     12   28            NaN          NaN
363     12   29      full moon          NaN
364     12   30            NaN          NaN
365     12   31            NaN          NaN

[366 rows x 4 columns]

In [ ]:
# moon_phases 데이터 프레임에 일자 정보를 datatime으로 변환하여 date컬럼 추가 20200428
moon_phases['date'] = pd.to_datetime(2020 * 10000 +moon_phases['month'] * 100 + moon_phases['day'], format='%Y%m%d')
moon_phases

     month  day      moonphase specialevent       date
0        1    1            NaN          NaN 2020-01-01
1        1    2  first quarter          NaN 2020-01-02
2        1    3            NaN          NaN 2020-01-03
3        1    4            NaN          NaN 2020-01-04
4        1    5            NaN          NaN 2020-01-05
..     ...  ...            ...          ...        ...
361     12   27            NaN          NaN 2020-12-27
362     12   28            NaN          NaN 2020-12-28
363     12   29      full moon          NaN 2020-12-29
364     12   30            NaN          NaN 2020-12-30
365     12   31            NaN          NaN 2020-12-31

[366 rows x 5 columns]

In [48]:
moon_phases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month         366 non-null    int64
 1   day           366 non-null    int64
 2   moonphase     50 non-null     object
 3   specialevent  10 non-null     object
 4   date          366 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 14.4+ KB

## 달의 위상 데이터를 숫자로 변환

In [53]:
moon_phases['moonphase'].unique()

<StringArray>
[nan, 'first quarter', 'full moon', 'third quarter', 'new moon']
Length: 5, dtype: str

In [54]:
# 달의 위상 데이터를 숫자로 변환하기
phase = {'new moon': 0, 'first quarter': 0.5, 'third quarter': 0.5, 'full moon': 1}

In [57]:
# 달의위상 데이터프레임에 phases데이터를 이용하여 백분율 컬럼(percentage) 새롭게 추가하기
moon_phases['percentage'] = moon_phases['moonphase'].map(phase)
moon_phases

     month  day      moonphase specialevent       date  percentage
0        1    1            NaN          NaN 2020-01-01         NaN
1        1    2  first quarter          NaN 2020-01-02         0.5
2        1    3            NaN          NaN 2020-01-03         NaN
3        1    4            NaN          NaN 2020-01-04         NaN
4        1    5            NaN          NaN 2020-01-05         NaN
..     ...  ...            ...          ...        ...         ...
361     12   27            NaN          NaN 2020-12-27         NaN
362     12   28            NaN          NaN 2020-12-28         NaN
363     12   29      full moon          NaN 2020-12-29         1.0
364     12   30            NaN          NaN 2020-12-30         NaN
365     12   31            NaN          NaN 2020-12-31         NaN

[366 rows x 6 columns]

In [57]:
moon_phases.sample(10)

     month  day      moonphase    specialevent       date  percentage
256      9   13            NaN             NaN 2020-09-13         NaN
289     10   16       new moon  super new moon 2020-10-16         0.0
363     12   29      full moon             NaN 2020-12-29         1.0
75       3   16  third quarter             NaN 2020-03-16         0.5
155      6    4            NaN             NaN 2020-06-04         NaN
189      7    8            NaN             NaN 2020-07-08         NaN
158      6    7            NaN             NaN 2020-06-07         NaN
90       3   31            NaN             NaN 2020-03-31         NaN
182      7    1            NaN             NaN 2020-07-01         NaN
196      7   15            NaN             NaN 2020-07-15         NaN

## 불필요한 컬럼 삭제

In [ ]:
# 각 데이터 프레임에서 불필요한 컬럼 삭제하기

In [60]:
constellations = constellations.drop(columns=['besttime'])
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [63]:
meteor_showers = meteor_showers.drop(columns=['startmonth', 'startday','endmonth', 'endday', 'preferredhemisphere' ])
meteor_showers

           name   radiant  bestmonth          hemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5  northern, southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

In [69]:
moon_phases = moon_phases.drop(columns=['month', 'day', 'moonphase','specialevent' ])
moon_phases

          date  percentage
0   2020-01-01         NaN
1   2020-01-02         0.5
2   2020-01-03         NaN
3   2020-01-04         NaN
4   2020-01-05         NaN
..         ...         ...
361 2020-12-27         NaN
362 2020-12-28         NaN
363 2020-12-29         1.0
364 2020-12-30         NaN
365 2020-12-31         NaN

[366 rows x 2 columns]

In [27]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

## 달의 위상 누락값 처리

In [74]:
# 달의위상 데이터 프레임에서 percentage 컬럼의 결측치 처리하기
moon_phases['percentage'] = moon_phases['percentage'].ffill().fillna(0)
moon_phases

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [78]:
cities

                        city  latitude               country
0                  Abu Dhabi     24.47  United Arab Emirates
1                      Abuja      9.07               Nigeria
2                      Accra      5.55                 Ghana
3                  Adamstown    -25.07      Pitcairn Islands
4                Addis Ababa      9.02              Ethiopia
..                       ...       ...                   ...
251  Abidjan(former capital)      6.82           Ivory Coast
252                  Yaounde      3.87              Cameroon
253          Yaren(de facto)     -0.53                 Nauru
254                  Yerevan     40.18               Armenia
255                   Zagreb     45.82               Croatia

[256 rows x 3 columns]

# 데이터 분석

In [ ]:
도시의 위도를 확인 cities
위도를 사용해서 해당 도시에 표시되는 별자리 확인 constellations
별자리를 사용해서 해당 도시에서 볼수 있는 유성우 확인 meteor_showers
유성우를 사용해서 해당 유성우를 볼 수 있는 날짜 확인
날짜를 사용해서 달의 위상값이 가장 작은 최적 날짜 확인 moon_phases

마지막으로 사용자에게 기분좋은 문구 반환

cities -> constellations -> meteor_showers -> moon_phases
      위도정보           별자리 -> 유성우    관측가능기간    가장 어두운날

## 위도 조회

In [ ]:
지정된 도시에서 각 유성우를 볼 수 있는 가능성이 높은 날짜를 예측하려고 합니다.

In [10]:
# 도시 데이터프레임에서 검색한 열(검색한 도시의 위도)만 가져오기
# dframe.loc[조건, 가져올 컬럼 이름] 아래는 'Abu Dhabi'의 결과

print(cities.loc[cities['city'] == 'Abu Dhabi', 'latitude'].iloc[0])
# 24.27

24.47

### 도시명 입력 후 위도 반환

In [ ]:
# 도시명을 입력하면 위도를 반환하는 함수 만들기
def predict_best_meteor_shower_viewing(city):
    latitude = cities.loc[cities['city'] == city, 'latitude'].iloc[0]
    return latitude

In [15]:
print(predict_best_meteor_shower_viewing('Abu Dhabi'))

24.47

In [16]:
print(predict_best_meteor_shower_viewing('Seoul'))

37.55

## 특정 위도에서 볼 수 있는 별자리 조회

In [105]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [24]:
# 24.47 혹은 37.55 위도값으로 관측 가능한 별자리 리스트를 반환
# ['Lyra','Aquarius','Orion', 'Perseus']

latitude = 37.55
constellations.loc[(constellations['latitudestart'] >= latitude) & (latitude >= constellations['latitudeend']), 'constellation'].to_list()

['Lyra', 'Aquarius', 'Orion', 'Perseus']

In [25]:
# 도시명을 입력하면 위도와 별자리 리스트를 반환하는 함수 만들기

def predict_best_meteor_shower_viewing(city):
    
    latitude = cities.loc[cities['city'] == city, 'latitude'].iloc[0]

    constellations_list = constellations.loc[(constellations['latitudestart'] >= latitude) & (latitude >= constellations['latitudeend']), 'constellation'].to_list()

    return latitude, constellations_list

In [28]:
predict_best_meteor_shower_viewing('Busan')

IndexError: single positional indexer is out-of-bounds

In [26]:
# 뉴질랜드 웰링턴으로 확인
predict_best_meteor_shower_viewing('Wellington')

(np.float64(-41.28), ['Aquarius', 'Orion'])

In [27]:
predict_best_meteor_shower_viewing('Seoul')

(np.float64(37.55), ['Lyra', 'Aquarius', 'Orion', 'Perseus'])

## 문자 안내 출력

In [ ]:
# 도시명을 입력히면 위도와 별자리리스트와 메시지를 반환하는 함수

def predict_best_meteor_shower_viewing(city):

    
    return latitude, constellations_list, meteor_shower_string

In [140]:
predict_best_meteor_shower_viewing('Busan')

'아쉽지만 Busan에서는 별자리 관측이 불가능합니다 ㅠㅜ;'

In [141]:
wellington = predict_best_meteor_shower_viewing('Wellington')
wellington

(np.float64(-41.28),
 ['Aquarius', 'Orion'],
 '와우 Wellington에서는 별자리 관측이 가능합니다 ^^')

## 유성우 관측 기간 조회(선택한 도시에서 관측 가능한 별자리 추출)

In [142]:
meteor_showers.head()

           name   radiant  bestmonth preferredhemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5            southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

In [143]:
wellington

(np.float64(-41.28),
 ['Aquarius', 'Orion'],
 '와우 Wellington에서는 별자리 관측이 가능합니다 ^^')

In [ ]:
# 유성우 관측 시작일 가져오기
# 여기서는 Wellington의 결과값을 가지고 조회

Timestamp('2020-04-19 00:00:00')

In [ ]:
# 유성우 관측 종료일

Timestamp('2020-05-28 00:00:00')

In [ ]:
# 별자리 근처 유성우 이름 추출

'Eta Aquarids'

In [ ]:
# 여러 유성우 처리하기 및 유성우 근처 별자리 이름 가져오기

Eta Aquarids 2020-04-19 00:00:00 2020-05-28 00:00:00
Orionids 2020-10-02 00:00:00 2020-11-07 00:00:00

## 달의 위상 최저치 추출

In [ ]:
달 위상의 최소값(달에서 반사되는 빛의 최소량)을 찾을 수 있습니다. 이 예측 함수에서는 첫 번째 날짜만 확인합니다.

In [ ]:
# 가장 어두운 날 찾기
moon_phase_list['percentage'].idxmin() # 가장 백분율이 적은 행 인덱스 반환

np.int64(112)

In [173]:
best_moon_date.to_pydatetime().strftime('%Y년 %m월 %d일')

'2020년 04월 22일'

In [224]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [198]:
meteor_showers

           name   radiant bestmonth preferredhemisphere
0        Lyrids      Lyra     april            northern
1  Eta Aquarids  Aquarius       may            southern
2      Orionids     Orion   october  northern, southern
3      Perseids   Perseus    august            northern
4       Leonids       Leo  november  northern, southern

## 최적의 유성우 관측일

In [ ]:
# 도시명을 입력하면 관측가능한 유성우에 대한 정보를 알려주는 함수 작성하기

def predict_best_meteor_shower_viewing(city):
    
    return meteor_shower_string

In [217]:
print(predict_best_meteor_shower_viewing('New York'))

아쉽지만 New York에서는 별자리 관측이 불가능합니다 ㅠㅜ;

In [222]:
print(predict_best_meteor_shower_viewing('Wellington'))

와우 Wellington에서는 별자리 관측이 가능합니다 ^^

Eta Aquarids를 보기 위해서는 Aquarius 자리를 향해서 2020년 04월 22일에 보는걸 추천드려요!!
Orionids를 보기 위해서는 Orion 자리를 향해서 2020년 10월 16일에 보는걸 추천드려요!!

In [ ]:
print(predict_best_meteor_shower_viewing('Seoul'))

Seoul에서는 별자리 관측이 가능합니다:

Lyrids를 잘 보려면 Lyra자리 위치를 향하여 April 22, 2020보면 됩니다.
Eta Aquarids를 잘 보려면 Aquarius자리 위치를 향하여 April 22, 2020보면 됩니다.
Orionids를 잘 보려면 Orion자리 위치를 향하여 October 16, 2020보면 됩니다.
Perseids를 잘 보려면 Perseus자리 위치를 향하여 July 20, 2020보면 됩니다.

In [223]:
print(predict_best_meteor_shower_viewing('Abu Dhabi'))

와우 Abu Dhabi에서는 별자리 관측이 가능합니다 ^^

Lyrids를 보기 위해서는 Lyra 자리를 향해서 2020년 04월 22일에 보는걸 추천드려요!!
Eta Aquarids를 보기 위해서는 Aquarius 자리를 향해서 2020년 04월 22일에 보는걸 추천드려요!!
Orionids를 보기 위해서는 Orion 자리를 향해서 2020년 10월 16일에 보는걸 추천드려요!!
Perseids를 보기 위해서는 Perseus 자리를 향해서 2020년 07월 20일에 보는걸 추천드려요!!

# 항아 유성우 데이터 추가

In [226]:
# 항아 유성우 데이터 추가하기
change_meteor_shower = {'name' : "Chang\'e", 'radiant' : 'Draco', 'bestmonth' : 'october', 'startmonth': 'october', 'startday' : 1,
                        'endmonth' : 'october', 'endday' : 31, 'hemisphere' : 'northern', 'preferredhemisphere' : 'northern' }
change_meteor_shower_df = pd.DataFrame(change_meteor_shower,index = [0])
change_meteor_shower_df

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Chang'e,Draco,october,october,1,october,31,northern,northern

In [227]:
# meteorshowers.csv 파일 읽어와서 new_meteor_showers 변수에 저장
new_meteor_showers = pd.read_csv('data/meteorshowers.csv')
new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [ ]:
# new_meteor_showers 데이터프레임에 change_meteor_shower_df 데이터프레임 추가하기 concat
new_meteor_showers = pd.concat([new_meteor_showers, change_meteor_shower_df], ignore_index=True)
new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"
5,Chang'e,Draco,october,october,1,october,31,northern,northern

In [229]:
# Chang'e 유성우에 대해 Draconids 유성우가 10월 초에 발생할 가능성이 높은 용자리를 선택합니다. 이 유성우를 가상 유성우의 참조로 사용
# 용자리 항목 추가하기기
draco_constellation = {'constellation' : 'Draco', 'bestmonth' : 'july', 'latitudestart' : 90, 'latitudeend' : -15, 'besttime' :2100, 'hemisphere' : 'northern'}
draco_constellation_df = pd.DataFrame(draco_constellation, index = [0])
draco_constellation_df

  constellation bestmonth  latitudestart  latitudeend  besttime hemisphere
0         Draco      july             90          -15      2100   northern

In [230]:
# 별자리 파일 읽어와서 new_constellations에 저장하기
new_constellations = pd.read_csv('data/constellations.csv')
new_constellations

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

In [231]:
# new_constellations 데이터프레임에 draco_constellation_df 추가하기 concat
new_constellations =  pd.concat([new_constellations, draco_constellation_df], ignore_index=True)# Todo Here
new_constellations

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern
5         Draco      july             90          -15     2100   northern

In [232]:
# new_meteor_showers 데이터프레임 월명 매핑
new_meteor_showers['startmonth'] = new_meteor_showers['startmonth'].map(months)
new_meteor_showers['bestmonth'] = new_meteor_showers['bestmonth'].map(months)
new_meteor_showers['endmonth'] = new_meteor_showers['endmonth'].map(months)
new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,8,24,northern,northern
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern"
5,Chang'e,Draco,10,10,1,10,31,northern,northern

In [233]:
# new_constellations 데이터프레임 월명 매핑
new_constellations['bestmonth'] = new_constellations['bestmonth'].map(months)
new_constellations

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern
3       Perseus         12             90          -35    21:00   northern
4           Leo          4             90           65    21:00   northern
5         Draco          7             90          -15     2100   northern

In [234]:
# new_meteor_showers 날짜형식 바꿔서 새로운 컬럼으로 추가 startdate, enddate
new_meteor_showers['startdate'] = pd.to_datetime(2020 * 10000 + 
                                             new_meteor_showers['startmonth'] * 100 + 
                                             new_meteor_showers['startday'],
                                             format = '%Y%m%d')
new_meteor_showers['enddate'] = pd.to_datetime(2020 * 10000 + 
                                             new_meteor_showers['endmonth'] * 100 + 
                                             new_meteor_showers['endday'],
                                             format = '%Y%m%d')

new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14,2020-08-24
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06,2020-11-30
5,Chang'e,Draco,10,10,1,10,31,northern,northern,2020-10-01,2020-10-31

In [ ]:
# 도시명을 입력히면 위도를 반환하는 함수
def predict_best_meteor_shower_viewing(city):


    return meteor_shower_string

In [236]:
print(predict_best_meteor_shower_viewing('Beijing'))

Beijing에서는 별자리 관측이 가능합니다:

Lyrids를 잘 보려면 Lyra자리 위치를 향하여 2020년 04월 22일에 보면 됩니다.
Eta Aquarids를 잘 보려면 Aquarius자리 위치를 향하여 2020년 04월 22일에 보면 됩니다.
Orionids를 잘 보려면 Orion자리 위치를 향하여 2020년 10월 16일에 보면 됩니다.
Perseids를 잘 보려면 Perseus자리 위치를 향하여 2020년 07월 20일에 보면 됩니다.
Chang'e를 잘 보려면 Draco자리 위치를 향하여 2020년 10월 16일에 보면 됩니다.